# Generated by Django 4.1.5 on 2023-01-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('blood_grp', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('status', models.CharField(default='active', max_length=20)),
                ('pic', models.ImageField(default='static/default-user.png', upload_to='patient/')),
            ],
            options={
                'db_table': 'patient_tb',
            },
        ),
    ]
